name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v2
        id: github-app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ steps.github-app-token.outputs.token }}"

      - name: Enable auto-merge for GitHub Actions updates
        if: |
          steps.metadata.outputs.package-ecosystem == 'github_actions' &&
          (steps.metadata.outputs.update-type == 'version-update:semver-major' ||
           steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
           steps.metadata.outputs.update-type == 'version-update:semver-patch')
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.github-app-token.outputs.token }}

      - name: Enable auto-merge for Terraform patch updates
        if: |
          steps.metadata.outputs.package-ecosystem == 'terraform' &&
          steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.github-app-token.outputs.token }}
